### PR TITLE
Add a "-p" option to all mkdir commands

### PR DESCRIPTION
**Pull request by kowh-ai**
This should be good practice **especially** if using the `ONBUILD` Docker command

### CODE REVIEW

**Comment by kowh-ai** [comment]
@wardi - this PR may fix the 2 issues [ckan-docker-base #192](https://github.com/ckan/ckan-docker/issues/192) and [ckan-docker #93](https://github.com/ckan/ckan-docker-base/issues/93) however I'm scratching my head as to what exactly is going on as the 2 issues are using the alpine images and although they did significantly change with [simplify repo change](https://github.com/ckan/ckan-docker-base/pull/85) the build instructions in the Dockerfile did not change...much

**Review by avdata99 — APPROVED** [review]
I assume only ONBUILD commands requires the `-p` param and we can skip the others

**Review by duttonw — APPROVED** [review]
It does not hurt to have the -p on all mkdir, so that it also handles parents being created if missed prior (as well as if already existing)

**Comment by kowh-ai** [comment]
Yes, I think getting rid of all `ONBUILD` instructions is a good idea

**Comment by amercader** [comment]
This looks good, @kowh-ai can you:

* Merge #95 to main
* Merge main to this branch to make sure all tests pass
* Merge this PR
* Create a new release to trigger the publication of images with the fix
* Close all related issues

**Pull request merged**
