### PR TITLE
Add CKAN 2.11 images

### PR DESCRIPTION
**Pull request by amercader**
These are the same py3.10 based ones as the master ones.

There's lots of duplicated files, we should aim to have a common directory for these unless a specific version needs to override a particular file for some reason.

### CODE REVIEW

**Comment by amercader** [comment]
Images pushed to [Docker Hub](https://hub.docker.com/repository/docker/ckan/ckan-base/tags?page=&page_size=&ordering=&name=2.11)

**Review by kowh-ai — APPROVED** [review]
@amercader - both base and dev images build OK

**Comment by kowh-ai** [comment]
@amercader - images build fine however I get errors when using these 2 new images 

1. Using the base image I get an error when adding a new resource to a dataset
Screenshot 2024-06-28 at 2 20 52 pm

2. Using the dev image I get a different error 

Screenshot 2024-06-28 at 2 35 44 pm

Screenshot 2024-06-28 at 2 35 59 pm

I can work on this next week to see what config options may be missing here

**Comment by amercader** [comment]
Thanks @kowh-ai 1 is probably a problem with my fix in https://github.com/ckan/ckan/pull/8284 and 2 looks like a networking problem with the datapusher container. I'll investigate as well

**Comment by amercader** [comment]
Can you review and merge https://github.com/ckan/ckan/pull/8310 @kowh-ai, that should take care of the first exception

**Comment by amercader** [comment]
Just tried issue 2 and worked for me. Make sure that `CKAN__DATAPUSHER__CALLBACK_URL_BASE` and `DATAPUSHER_REWRITE_URL` are correctly set using `ckan-dev` instead of `ckan`.
We probably need separate `.env.example` and `.env.dev.example` files because there's a few of these options that are different across environments.

**Comment by kowh-ai** [comment]
@amercader - Yes all of the images work for me now (after a day of testing). I did have the same networking (cannot connect to datapusher) issues in **2.10** and **2.11** _and_ I had updated `CKAN__DATAPUSHER__CALLBACK_URL_BASE` and `DATAPUSHER_REWRITE_URL` to use `ckan-dev` but they did "go away" and I couldn't recreate the same error. Anyway, I'll create a PR on the ckan-docker repo for a README change to detail what to change in the `.env` file when moving from **base** to **dev** mode

**Comment by amercader** [comment]
@kowh-ai yes I had different issues when recreating environments, specially when switching between the prod/dev ones. Basically you need to remove everything including volumes to avoid issues. I suspect the site_packages one is to blame in many cases , eg packages from project images not being installed

**Comment by wardi** [comment]
needing to update the .env and using/not using `-f docker-compose.dev.yml` isn't ideal. Maybe we can use the same docker compose for both dev and prod and use a setting to switch instead?

**Pull request merged**
