### PR TITLE
Add actions to build and push images to Docker Hub

### PR DESCRIPTION
**Pull request by amercader**
As discussed in https://github.com/ckan/ckan/issues/8143, we want to automate the publication of artifacts as much as possible, in this case the building and pushing of CKAN Docker images to Docker hub.

This PR adds a new reusable workflow that is call for each CKAN version to build.

The [actions](https://github.com/ckan/ckan-docker-base/actions) work but there's stuff we need to decide before merging.

1. The biggest question is when or how to trigger a build/push, right now these are triggered on every push to this repo, but this is not what we want. Some options:

  * When we push some tag(s)
  * When there's a new [release](https://github.com/ckan/ckan-docker-base/releases) created
  * When we add some labels to a Pull request

2. There are CKAN tags hardcoded in the worflow files, so on every patch release we would need to update these files. There's probably a way to centralize these, reading them from an env var or a file in the repo

### CODE REVIEW

**Comment by wardi** [comment]
is it better to reference the latest ckan-X.Y image instead of a specific point release? IIUC the docker registry lets us update these links, users can get the latest by building and we don't need to update the tags inside the repo on every ckan-docker-base release.

**Comment by kowh-ai** [comment]
Maybe once a new release has been pushed to DockerHub ie: `2.10.4` or `2.11.0` this remains ‘untouched’ as an image and can be used as a “point in time” release. Subsequent builds of, for instance `2.10` (which actually would be `2.10.4`) could be tagged as `2.10.latest`. These could be generated weekly.

**Comment by amercader** [comment]
@kowh-ai @wardi This is now ready for review. The latest changes to simplify the repo made this much easier and the workflows are pretty minimal and shouldn't require updates (e.g. version numbers) going forward. 
The bulk of new logic is to [generate the right image tags](https://github.com/ckan/ckan-docker-base/pull/73/files#diff-a85b56425efae71b4943b61b12218c1d3132bf336bd0b560b8407b92ce411656R35) depending on what version we are building :)

Right now publishing will be triggered when a new release is "released". According to the [docs](https://docs.github.com/en/webhooks/webhook-events-and-payloads#release) this  means that:

> A release was published, or a pre-release was changed to a release

Seems like a good event to trigger it, as we can create drafts without publishing the images yet

**Review by kowh-ai — APPROVED** [review]
Nice work @amercader - it's nice and lean

**Pull request merged**
